apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  chart:
    spec:
      # renovate: datasource=helm
      # chartname=homepage
      # url=http://jameswynn.github.io/helm-charts
      version: 2.1.0
