apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jameswynn
  namespace: homepage
spec:
  interval: 10m0s
  provider: generic
  url: http://jameswynn.github.io/helm-charts
