apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tofu-controller
  namespace: tofu-controller
spec:
  chart:
    spec:
      chart: tofu-controller
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: tofu-controller
      version: '0.16.0-rc.5'
  interval: 10m0s
  releaseName: tofu-controller
  values:
    allowCrossNamespaceRefs: true
    runner:
      serviceAccount:
        allowedNamespaces: []
