apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tofu-controller
  namespace: tofu-controller
spec:
  interval: 10m0s
  provider: generic
  url: https://flux-iac.github.io/tofu-controller/
