apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: robusta
  namespace: robusta
spec:
  interval: 10m0s
  provider: generic
  url: https://robusta-charts.storage.googleapis.com
