---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homelab-clusters-addons-apps
  namespace: cluster-room101-a7d-mc
spec:
  dependsOn:
    - name: homelab-clusters-addons-prereqs
      namespace: cluster-room101-a7d-mc
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: homelab-clusters-addons
    namespace: flux-system
  path: ./flux/apps/room101-a7d-mc
  decryption:
    provider: sops
    secretRef:
      name: sops-age-addons
  prune: true
  wait: true
  suspend: false
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: homelab-clusters-addons-vars
        optional: false
