---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homelab-clusters-addons-configs
  namespace: cluster-room101-a7d-mc
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: homelab-clusters-addons
    namespace: flux-system
  path: ./flux/configs/room101-a7d-mc
  prune: true
  wait: true
  suspend: false
