---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homelab-clusters-addons-prereqs
  namespace: cluster-room101-a7d-mc
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: homelab-clusters-addons
    namespace: flux-system
  path: ./flux/clusters/room101-a7d-mc/prereqs
  prune: true
  wait: true
  suspend: false
