apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-prometheus-stack-helmrelease.yaml
  - kube-prometheus-stack-helmrepository.yaml
  - kube-prometheus-stack-namespace.yaml
  - configs/dashboards/configmap-flux-cluster.yaml
  - configs/podmonitors/podmonitor-flux-system.yaml
