apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: observability-stack-schedule-on-control-plane-nodes
  annotations:
    policies.kyverno.io/title: Add Tolerations for Control Plane Nodes
    policies.kyverno.io/category: Other
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.7.1
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      This policy adds the toleration to allow pods to schedule on
      control plane nodes.
spec:
  rules:
  - name: control-plane-toleration
    match:
      any:
      - resources:
          kinds:
          - Pod
    preconditions:
      any:
      - key: "node-role.kubernetes.io/control-plane"
        operator: AnyNotIn
        value: "{{ request.object.spec.tolerations[].key || `[]` }}"
    mutate:
      patchesJson6902: |-
        - op: add
          path: "/spec/tolerations/-"
          value:
            key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
