apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: arc-scale-set
  namespace: arc-runners
spec:
  interval: 10m0s
  type: oci
  url: oci://ghcr.io/actions/actions-runner-controller-charts
