apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-scale-set
  namespace: arc-runners
spec:
  chart:
    spec:
      chart: gha-runner-scale-set
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: arc
      version: '0.12.1'
  interval: 10m0s
  releaseName: scale-set-room101-a7d-prod1
  values:
    githubConfigUrl: "https://github.com/a7d-corp"
    githubConfigSecret: arc-runners-github-auth
    minRunners: 0
    maxRunners: 10
    containerMode:
      type: "kubernetes"
      kubernetesModeWorkVolumeClaim:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "truenas-nfs"
        resources:
          requests:
            storage: 1Gi
