apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: echo-server
  namespace: echo-server
spec:
  chart:
    spec:
      chart: echo-server
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ealenn
  interval: 10m0s
  releaseName: echo-server
  values:
    ingress:
      enabled: true
      hosts:
        - host: echo-server.${FQDN_BASE}
          paths:
            - /
      ingressClassName: nginx
