apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: echo-server
  namespace: echo-server
spec:
  chart:
    spec:
      chart: echo-server
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ealenn
      version: '>=0.5.0 <1.0.0'
  interval: 10m0s
  releaseName: echo-server
  values:
    ingress:
      enabled: true
      annotations:
      hosts:
        - host: echo-server.${FQDN_BASE}
          paths:
            - /
      ingressClassName: nginx
      tls:
        - secretName: echo-server-tls
          hosts:
            - echo-server.${FQDN_BASE}
