apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/actions-runner-controller/
  - arc/helmrelease-version.yaml
#  - arc/secret-arc-runners-github-auth.yaml
  - ../base/descheduler/
  - descheduler/helmrelease-version.yaml
  - ../base/echo-server/
  - echo-server/helmrelease-version.yaml
  - ../base/reflector/
  - reflector/helmrelease-version.yaml
  - ../base/tofu-controller/
  - tofu-controller/helmrelease-version.yaml
