apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/actions-runner-controller/
#  - arc/secret-arc-runners-github-auth.yaml
  - ../base/descheduler/
  - ../base/echo-server/
  - ../base/reflector/
  - ../base/tofu-controller/
patches:
  - path: arc/helmrelease-version.yaml
  - path: descheduler/helmrelease-version.yaml
  - path: echo-server/helmrelease-version.yaml
  - path: reflector/helmrelease-version.yaml
  - path: tofu-controller/helmrelease-version.yaml
