apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/actions-runner-controller/
  - ../base/descheduler/
  - ../base/echo-server/
  - ../base/reflector/
  - ../base/tofu-controller/
