apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  chart:
    spec:
      # renovate: datasource=helm
      # chartname=metrics-server
      # url=https://kubernetes-sigs.github.io/metrics-server/
      version: 3.13.0
