apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: hass.analbeard.com
  namespace: dnsendpoints
spec:
  endpoints:
  - dnsName: hass.analbeard.com
    recordTTL: 180
    recordType: CNAME
    targets:
    - lab.a7d.dev
