apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: opnsense.int.analbeard.com
  namespace: dnsendpoints
spec:
  endpoints:
  - dnsName: opnsense.int.analbeard.com
    recordTTL: 180
    recordType: CNAME
    targets:
    - proxmox-proxy.int.a7d.dev
