apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: rainloop.analbeard.com
  namespace: dnsendpoints
spec:
  endpoints:
  - dnsName: rainloop.analbeard.com
    recordTTL: 180
    recordType: CNAME
    targets:
    - ${EXTERNAL_FQDN_TARGET}
