apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: finances.a7d.dev
  namespace: dnsendpoints
spec:
  endpoints:
  - dnsName: finances.a7d.dev
    recordTTL: 180
    recordType: CNAME
    targets:
    - ${EXTERNAL_FQDN_TARGET}
