apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- dnsendpoint-a-proxmox-proxy-int-a7d-dev.yaml
- dnsendpoint-cname-accounting-a7d-dev.yaml
- dnsendpoint-cname-finances-a7d-dev.yaml
- dnsendpoint-cname-frigate-analbeard-com.yaml
- dnsendpoint-cname-hass-analbeard-com.yaml
- dnsendpoint-cname-hoarder-a7d-dev.yaml
- dnsendpoint-cname-n8n-a7d-dev.yaml
- dnsendpoint-cname-ntfy-int-a7d-dev.yaml
- dnsendpoint-cname-opnsense-int-a7d-dev.yaml
- dnsendpoint-cname-opnsense-int-analbeard-com.yaml
- dnsendpoint-cname-plex-analbeard-com.yaml
- dnsendpoint-cname-proxmox-virt-lab-analbeard-com.yaml
- dnsendpoint-cname-rainloop-analbeard-com.yaml
- dnsendpoint-cname-status-a7d-dev.yaml
- dnsendpoint-cname-transmission-analbeard-com.yaml
- namespace.yaml
