apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- dnsendpoint-accounting-a7d-dev.yaml
- dnsendpoint-finances-a7d-dev.yaml
- dnsendpoint-frigate-analbeard-com.yaml
- dnsendpoint-hass-analbeard-com.yaml
- dnsendpoint-hoarder-a7d-dev.yaml
- dnsendpoint-n8n-a7d-dev.yaml
- dnsendpoint-plex-analbeard-com.yaml
- dnsendpoint-proxmox-virt-lab-analbeard-com.yaml
- dnsendpoint-rainloop-analbeard-com.yaml
- dnsendpoint-status-a7d-dev.yaml
- dnsendpoint-transmission-analbeard-com.yaml
- namespace.yaml
