apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-controller
  namespace: arc-system
spec:
  chart:
    spec:
      # renovate: datasource=docker
      # chartname=gha-runner-scale-set-controller
      # url=oci://ghcr.io/actions/actions-runner-controller-charts
      version: '0.12.1'
