apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: atlantis
  namespace: atlantis
spec:
  chart:
    spec:
      # renovate: datasource=helm
      # chartname=atlantis
      # url=https://runatlantis.github.io/helm-charts
      version: 5.18.1
