apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: atlantis
  namespace: atlantis
spec:
  chart:
    spec:
      # helmchart: datasource=helm chartname=atlantis url=https://runatlantis.github.io/helm-charts/atlantis
      version: 5.18.0
