apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: minio-operator
spec:
  chart:
    spec:
      # renovate: datasource=helm
      # chartname=operator
      # url=https://operator.min.io
      version: 7.1.1
