apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
  namespace: descheduler
spec:
  chart:
    spec:
      chart: descheduler
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: descheduler
      version: 0.33.0
  interval: 10m0s
  releaseName: descheduler
  values:
    kind: Deployment
    deschedulerPolicy:
      profiles:
        - name: LowCPUUtilization
          pluginConfig:
            - name: DefaultEvictor
              args:
                ignorePvcPods: true
                evictLocalStoragePods: true
            - name: LowNodeUtilization
              args:
                thresholds:
                  cpu: 40
                targetThresholds:
                  cpu: 70
          plugins:
            balance:
              enabled:
                - LowNodeUtilization
        - name: LowMemoryUtilization
          pluginConfig:
            - name: DefaultEvictor
              args:
                ignorePvcPods: true
                evictLocalStoragePods: true
            - name: LowNodeUtilization
              args:
                thresholds:
                  memory: 40
                targetThresholds:
                  memory: 70
          plugins:
            balance:
              enabled:
                - LowNodeUtilization
