apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chart:
    spec:
      # renovate: datasource=helm
      # chartname=kube-prometheus-stack
      # url=https://prometheus-community.github.io/helm-charts
      version: 77.14.0
