apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: monitoring
spec:
  chart:
    spec:
      # renovate: datasource=helm
      # chartname=alloy
      # url=https://grafana.github.io/helm-charts
      version: 1.2.1
