apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: goldilocks
spec:
  chart:
    spec:
      # renovate: datasource=helm
      # chartname=goldilocks
      # url=https://charts.fairwinds.com/stable
      version: 10.1.0
