apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
  namespace: descheduler
spec:
  chart:
    spec:
      # renovate: datasource=helm
      # chartname=descheduler
      # url=https://kubernetes-sigs.github.io/descheduler/
      version: 0.33.0
