apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
spec:
  chart:
    spec:
      chart: k8s-monitoring
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
  interval: 10m0s
  releaseName: alloy
  values:
    cluster:
      name: ${CLUSTER_NAME}
    destinations:
    - name: mimir
      type: prometheus
      url: http://mimir-nginx.monitoring.svc.cluster.local/api/v1/write
    clusterMetrics:
      enabled: true
    prometheusOperatorObjects:
      enabled: true
    alloy-metrics:
      enabled: true
    alloy-logs:
      enabled: true
    alloy-singleton:
      enabled: true
