apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vertical-pod-autoscaler
  namespace: vertical-pod-autoscaler
spec:
  chart:
    spec:
      # renovate: datasource=helm
      # chartname=vpa
      # url=https://charts.fairwinds.com/stable
      version: 4.8.0
