apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vertical-pod-autoscaler
  namespace: vertical-pod-autoscaler
spec:
  chart:
    spec:
      # helmchart: kubernetes/autoscaler
      version: 4.7.2
