apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vertical-pod-autoscaler
  namespace: vertical-pod-autoscaler
spec:
  chart:
    spec:
      chart: vertical-pod-autoscaler
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: fairwinds-stable
      version: 1.0.0
  interval: 10m0s
  releaseName: vpa
  values:
    updater:
      enabled: false
