apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  chart:
    spec:
      # renovate: datasource=helm
      # chartname=reflector
      # url=https://emberstack.github.io/helm-charts
      version: 9.1.30
