apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  chart:
    spec:
      # helmchart: emberstack/kubernetes-reflector
      version: 9.1.22
