apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tofu-controller
  namespace: tofu-controller
spec:
  chart:
    spec:
      # renovate: datasource=helm
      # chartname=tofu-controller
      # url=https://flux-iac.github.io/tofu-controller/
      version: '0.16.0-rc.5'
