apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tofu-controller
  namespace: tofu-controller
spec:
  chart:
    spec:
      # helmchart: flux-iac/tofu-controller
      version: '0.16.0-rc.5'
