apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  chart:
    spec:
      chart: reflector
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: emberstack
      version: 0.0.0
  interval: 10m0s
  releaseName: reflector
