apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  chart:
    spec:
      chart: reflector
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: emberstack
      version: '>=9.0.344 <10.0.0'
  interval: 10m0s
  releaseName: reflector
