apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: emberstack
  namespace: reflector
spec:
  interval: 10m0s
  provider: generic
  url: https://emberstack.github.io/helm-charts
