apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/atlantis/
  - atlantis/namespace-atlantis.yaml
  - atlantis/secret-atlantis-remote-credentials.yaml
  - atlantis/secret-atlantis-vault-credentials.yaml
  - atlantis/secret-atlantis-vcs-credentials.yaml
  - ../base/descheduler/
  - ../base/echo-server/
  - ../base/goldilocks/
  - ../base/homepage/
  - homepage/homepage-namespace.yaml
  - homepage/homepage-secret.yaml
  - ../base/kube-prometheus-stack/
  - kube-prometheus-stack/secret-grafana-admin-credentials.yaml
  - kube-prometheus-stack/secret-grafana-oauth-secrets.yaml
  - ../base/metrics-server/
  - ../base/octopus-energy/
  - ../base/reflector/
  - ../base/vertical-pod-autoscaler/
patches:
  - path: atlantis/helmrelease-version.yaml
    target:
      group: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: atlantis
  - path: descheduler/helmrelease-version.yaml
    target:
      group: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: descheduler
  - path: echo-server/helmrelease-version.yaml
    target:
      group: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: echo-server
  - path: goldilocks/helmrelease-version.yaml
    target:
      group: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: goldilocks
  - path: homepage/helmrelease-version.yaml
    target:
      group: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: homepage
  - path: kube-prometheus-stack/helmrelease-version.yaml
    target:
      group: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: kube-prometheus-stack
  - path: metrics-server/helmrelease-version.yaml
    target:
      group: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: metrics-server
  - path: reflector/helmrelease-version.yaml
    target:
      group: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: reflector
  - path: vertical-pod-autoscaler/helmrelease-version.yaml
    target:
      group: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: vertical-pod-autoscaler
