apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/atlantis/
  - atlantis/namespace-atlantis.yaml
  - atlantis/secret-atlantis-remote-credentials.yaml
  - atlantis/secret-atlantis-vault-credentials.yaml
  - atlantis/secret-atlantis-vcs-credentials.yaml
  - ../base/descheduler/
  - ../base/echo-server/
  - ../base/goldilocks/
  - ../base/homepage/
  - homepage/homepage-namespace.yaml
  - homepage/homepage-secret.yaml
  - ../base/kube-prometheus-stack/
  - kube-prometheus-stack/secret-grafana-admin-credentials.yaml
  - kube-prometheus-stack/secret-grafana-oauth-secrets.yaml
  - ../base/metrics-server/
  - ../base/minio-operator/
  - minio-operator/minio-operator-namespace.yaml
  - ../base/octopus-energy/
  - ../base/reflector/
  - ../base/vertical-pod-autoscaler/
patches:
  - path: atlantis/helmrelease-version.yaml
  - path: descheduler/helmrelease-version.yaml
  - path: echo-server/helmrelease-version.yaml
  - path: goldilocks/helmrelease-version.yaml
  - path: homepage/helmrelease-version.yaml
  - path: kube-prometheus-stack/helmrelease-version.yaml
  - path: metrics-server/helmrelease-version.yaml
  - path: minio-operator/helmrelease-version.yaml
  - path: reflector/helmrelease-version.yaml
  - path: vertical-pod-autoscaler/helmrelease-version.yaml
