apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: echo-server
  namespace: echo-server
spec:
  chart:
    spec:
      # renovate: datasource=helm
      # chartname=echo-server
      # url=https://ealenn.github.io/charts
      version: 0.5.0
