apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  chart:
    spec:
      # renovate: datasource=helm
      # chartname=grafana
      # url=https://grafana.github.io/helm-charts
      version: 9.4.0
