apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-controller
  namespace: arc-system
spec:
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: arc
      version: 0.0.0
  interval: 10m0s
  releaseName: gha-runner-scale-set-controller
